### ISSUE TITLE
Периодически возникает исключение 'Invalid character found in method name'

### ISSUE THREAD

**Issue by Freeongoo** [Tinkoff/invest-openapi-java-sdk#140]
Периодически возникает исключение:

```
2021-09-26 14:36:22,897 INFO Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:415)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:292)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Данного исключения раньше не наблюдал, сейчас стало возникать. Не понятно из-за чего происходит. При перезапуске исключения пропадает.

**Comment by zlumyo** [comment]
Закрываю тикет в связи с заморозкой репозитория
